

def gen_header():
    return (
        "import pandas as pd\n"
        "import numpy as np\n"
        "from datetime import datetime\n\n"
        "def dt(x):\n"
        "    # parse ISO-like dates (YYYY-MM-DD or YYYYMMDD)\n"
        "    if x is None: return pd.NaT\n"
        "    try:\n"
        "        import pandas as pd\n"
        "    except Exception:\n"
        "        pass\n"
        "    if pd.isna(x): return pd.NaT\n"
        "    s = str(x)\n"
        "    for fmt in ('%Y-%m-%d','%Y%m%d','%Y-%m-%dT%H:%M:%S'):\n"
        "        try:\n"
        "            return pd.to_datetime(s, format=fmt, errors='coerce')\n"
        "        except Exception: pass\n"
        "    return pd.to_datetime(s, errors='coerce')\n\n"
    )


def gen_adsl_flags():
    return gen_header() + (
        "def build_adsl(dm, ex, randdt_col='RANDDT'):\n"
        "    dm = dm.copy()\n"
        "    ex = ex.copy()\n"
        "    # Randomization date can come from DM or Derived; fallback to RFSTDTC\n"
        "    if randdt_col not in dm.columns:\n"
        "        if 'RFSTDTC' in dm.columns:\n"
        "            dm['RANDDT'] = dm['RFSTDTC'].map(dt)\n"
        "        else:\n"
        "            dm['RANDDT'] = pd.NaT\n"
        "    else:\n"
        "        dm['RANDDT'] = dm[randdt_col].map(dt)\n"
        "    if 'EXSTDTC' in ex.columns:\n"
        "        ex['EXSTDTC'] = ex['EXSTDTC'].map(dt)\n"
        "    dose_any = ex.groupby('USUBJID').apply(lambda d: d['EXSTDTC'].notna().any()).reset_index(name='dose_any')\n"
        "    adsl = dm[['USUBJID']].drop_duplicates().merge(dose_any, on='USUBJID', how='left')\n"
        "    adsl['dose_any'] = adsl['dose_any'].fillna(False)\n"
        "    adsl['SAFFL'] = adsl['dose_any'].map(lambda x: 'Y' if bool(x) else 'N')\n"
        "    itt = dm[['USUBJID','RANDDT']].drop_duplicates()\n"
        "    itt['ITTFL'] = itt['RANDDT'].notna().map({True:'Y',False:'N'})\n"
        "    adsl = adsl.merge(itt[['USUBJID','ITTFL']], on='USUBJID', how='left')\n"
        "    adsl['PPSFL'] = 'N'  # placeholder; apply SAP criteria\n"
        "    return adsl[['USUBJID','SAFFL','ITTFL','PPSFL']]\n"
    )


def gen_adtte_os():
    return gen_header() + (
        "def build_adtte_os(adsl, ds, ae=None, start_col='TRTSDT'):\n"
        "    # START date from ADSL\n"
        "    adsl = adsl.copy()\n"
        "    if start_col in adsl.columns:\n"
        "        adsl['STARTDT'] = adsl[start_col].map(dt)\n"
        "    elif 'RANDDT' in adsl.columns:\n"
        "        adsl['STARTDT'] = adsl['RANDDT'].map(dt)\n"
        "    else:\n"
        "        adsl['STARTDT'] = pd.NaT\n"
        "    # Death date from DS (DSDECOD contains 'DEATH')\n"
        "    ds = ds.copy()\n"
        "    ds['DSDT'] = pd.NaT\n"
        "    for c in ('DSSTDTC','DSDTC'):\n"
        "        if c in ds.columns:\n"
        "            ds['DSDT'] = ds[c].map(dt)\n"
        "            break\n"
        "    death = ds[ds.get('DSDECOD','').astype(str).str.upper().str.contains('DEATH', na=False)]\n"
        "    death = death[['USUBJID','DSDT']].dropna()\n"
        "    tte = adsl[['USUBJID','STARTDT']].merge(death, on='USUBJID', how='left')\n"
        "    tte['ADT'] = tte['DSDT']  # earliest event date; extend with other sources if needed\n"
        "    tte['CNSR'] = tte['ADT'].notna().map({True:0, False:1})\n"
        "    tte['AVAL'] = (tte['ADT'] - tte['STARTDT']).dt.days\n"
        "    # minimal structure\n"
        "    tte['PARAM'] = 'Overall Survival'\n"
        "    tte['PARAMCD'] = 'OS'\n"
        "    return tte[['USUBJID','PARAM','PARAMCD','STARTDT','ADT','CNSR','AVAL']]\n"
    )


def gen_adtte_pfs():
    return gen_header() + (
        "def build_adtte_pfs(adsl, rs, ds, start_col='TRTSDT'):\n"
        "    adsl = adsl.copy(); rs = rs.copy(); ds = ds.copy()\n"
        "    # start date\n"
        "    if start_col in adsl.columns:\n"
        "        adsl['STARTDT'] = adsl[start_col].map(dt)\n"
        "    elif 'RANDDT' in adsl.columns:\n"
        "        adsl['STARTDT'] = adsl['RANDDT'].map(dt)\n"
        "    else:\n"
        "        adsl['STARTDT'] = pd.NaT\n"
        "    # progression date in RS where progression/PD per RSSTRESC/RSDECOD\n"
        "    rs['RSDT'] = pd.NaT\n"
        "    for c in ('RSDTC','RSSTDTC'):\n"
        "        if c in rs.columns:\n"
        "            rs['RSDT'] = rs[c].map(dt)\n"
        "            break\n"
        "    prog = rs[(rs.get('RSSTRESC','').astype(str).str.upper().isin(['PD','PROGRESSION'])) | \
              (rs.get('RSDECOD','').astype(str).str.upper().str.contains('PROGRESS', na=False))]\n"
        "    prog = prog[['USUBJID','RSDT']].dropna().groupby('USUBJID', as_index=False).agg({'RSDT':'min'})\n"
        "    # death date from DS\n"
        "    ds['DSDT'] = pd.NaT\n"
        "    for c in ('DSSTDTC','DSDTC'):\n"
        "        if c in ds.columns:\n"
        "            ds['DSDT'] = ds[c].map(dt)\n"
        "            break\n"
        "    death = ds[ds.get('DSDECOD','').astype(str).str.upper().str.contains('DEATH', na=False)]\n"
        "    death = death[['USUBJID','DSDT']].dropna()\n"
        "    # earliest event: progression or death\n"
        "    ev = prog.merge(death, on='USUBJID', how='outer')\n"
        "    ev['ADT'] = ev[['RSDT','DSDT']].min(axis=1)\n"
        "    tte = adsl[['USUBJID','STARTDT']].merge(ev[['USUBJID','ADT']], on='USUBJID', how='left')\n"
        "    tte['CNSR'] = tte['ADT'].notna().map({True:0, False:1})\n"
        "    tte['AVAL'] = (tte['ADT'] - tte['STARTDT']).dt.days\n"
        "    tte['PARAM'] = 'Progression-Free Survival'\n"
        "    tte['PARAMCD'] = 'PFS'\n"
        "    return tte[['USUBJID','PARAM','PARAMCD','STARTDT','ADT','CNSR','AVAL']]\n"
    )
